---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agents-as-code-webhook
  namespace: agents-as-code-system
  labels:
    agents-as-code/route: webhook
spec:
  ingressClassName: nginx
  rules:
  - host: "webhook.%DOMAIN_NAME%"
    http:
      paths:
      - backend:
          service:
            name: agents-as-code-webhook
            port:
              number: 8080
        path: /
        pathType: Prefix
