---
apiVersion: v1
kind: Namespace
metadata:
  name: agents-as-code-system
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: agents-as-code
