---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yeet-controller
  namespace: yeet-system
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: yeet
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yeet-webhook
  namespace: yeet-system
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: yeet
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yeet-controller-clusterrole
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: yeet
rules:
  - apiGroups: ["agent.tekton.dev"]
    resources: ["repositories"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["agent.tekton.dev"]
    resources: ["repositories/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["agent.tekton.dev"]
    resources: ["agentruns"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["agent.tekton.dev"]
    resources: ["agentruns/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yeet-controller-clusterbinding
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: yeet
subjects:
  - kind: ServiceAccount
    name: yeet-controller
    namespace: yeet-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yeet-controller-clusterrole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yeet-webhook-clusterrole
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: yeet
rules:
  - apiGroups: ["agent.tekton.dev"]
    resources: ["repositories"]
    verbs: ["get", "list"]
  - apiGroups: ["agent.tekton.dev"]
    resources: ["agentruns"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yeet-webhook-clusterbinding
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: yeet
subjects:
  - kind: ServiceAccount
    name: yeet-webhook
    namespace: yeet-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yeet-webhook-clusterrole
