---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents-as-code-controller
  namespace: agents-as-code-system
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/part-of: agents-as-code
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: controller
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: agents-as-code
  template:
    metadata:
      labels:
        app: agents-as-code-controller
        app.kubernetes.io/name: controller
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: agents-as-code
        app.kubernetes.io/version: "devel"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: agents-as-code-controller
      containers:
        - name: controller
          image: "ko://github.com/theakshaypant/agents-as-code/cmd/controller"
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: health
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: health
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
