---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeet-controller
  namespace: yeet-system
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/part-of: yeet
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: controller
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: yeet
  template:
    metadata:
      labels:
        app: yeet-controller
        app.kubernetes.io/name: controller
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: yeet
        app.kubernetes.io/version: "devel"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: yeet-controller
      containers:
        - name: controller
          image: "ko://github.com/theakshaypant/yeet/cmd/controller"
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 8080
            - name: health
              containerPort: 8081
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: health
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: health
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
