---
apiVersion: v1
kind: Service
metadata:
  name: yeet-controller
  namespace: yeet-system
  labels:
    app: yeet-controller
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/part-of: yeet
spec:
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: yeet
