---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeet-webhook
  namespace: yeet-system
  labels:
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/part-of: yeet
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: yeet
  template:
    metadata:
      labels:
        app: yeet-webhook
        app.kubernetes.io/name: webhook
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: yeet
        app.kubernetes.io/version: "devel"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: yeet-webhook
      containers:
        - name: webhook
          image: "ko://github.com/theakshaypant/yeet/cmd/webhook"
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8082
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /live
              port: api
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /live
              port: api
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
