---
apiVersion: v1
kind: Service
metadata:
  name: agents-as-code-webhook
  namespace: agents-as-code-system
  labels:
    app: agents-as-code-webhook
    app.kubernetes.io/version: "devel"
    app.kubernetes.io/part-of: agents-as-code
spec:
  ports:
    - name: http-listener
      port: 8080
      protocol: TCP
      targetPort: 8082
  selector:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: agents-as-code
